version: '3.8'
services:
  gestio_parking:
    image: zakaria515/gestio_parking:latest
    ports:
      - "8080:8080"
  app_frontend:
    image: zakaria515/app-frontend:latest
    ports:
      - "3000:3000"
