name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: gestio_parking 
      run: mvn -B package --file pom.xml

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10.x'

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: gestio_parking
        file: gestio_parking/Dockerfile
        push: true
        tags: |
          zakaria515/gestio_parking:latest
          zakaria515/gestio_parking:${{ github.sha }}
          
    - name: Build and push front Docker image
      uses: docker/build-push-action@v2
      with:
        context: app-frontend
        file: app-frontend/Dockerfile
        push: true
        tags: |
          zakaria515/app-frontend:latest
          zakaria515/app-frontend:${{ github.sha }}          
